# Generated by Django 6.0.2 on 2026-03-03 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0003_delete_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del Concurso')),
                ('start_date', models.DateTimeField(verbose_name='Fecha inicio')),
                ('end_date', models.DateTimeField(verbose_name='Fecha fin')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Inscripción Abierta'), ('RUNNING', 'En Curso'), ('CLOSED', 'Finalizado')], default='DRAFT', max_length=10, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_contests', to='clubs.organization', verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
                'ordering': ['-start_date'],
            },
        ),
    ]
