# Generated by Django 6.0.2 on 2026-03-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('users', '0002_alter_fisher_options_remove_fisher_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Estado de Pago')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest', verbose_name='Concurso')),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.fisher', verbose_name='Pescador')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'unique_together': {('fisher', 'contest')},
            },
        ),
    ]
