# Generated by Django 6.0.2 on 2026-03-03 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_registration'),
        ('users', '0002_alter_fisher_options_remove_fisher_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=120, verbose_name='Especie')),
                ('length_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Medida (cm)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='captures/', verbose_name='Foto')),
                ('approved', models.BooleanField(default=False, verbose_name='Aprobada')),
                ('approved_by', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='contests.contest', verbose_name='Concurso')),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='users.fisher', verbose_name='Pescador')),
            ],
            options={
                'verbose_name': 'Captura',
                'verbose_name_plural': 'Capturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
