# Generated by Django 6.0.2 on 2026-03-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='competitor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de pescador'),
        ),
    ]
