# Generated by Django 6.0.2 on 2026-03-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_registration_competitor_number'),
        ('users', '0003_alter_fisher_options_fisher_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='users.fisher'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
