# Generated by Django 6.0.2 on 2026-03-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_registration_options_registration_qr_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
