# Generated by Django 6.0.2 on 2026-03-06 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_pushsubscription'),
        ('users', '0003_alter_fisher_options_fisher_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.contest'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='fisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fisher'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='length_cm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='capture',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='captures/'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='species',
            field=models.CharField(max_length=50),
        ),
    ]
