# Generated by Django 6.0.2 on 2026-03-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_alter_capture_contest_alter_capture_fisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='contests.contest'),
        ),
    ]
