# Generated by Django 6.0.2 on 2026-03-09 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0008_alter_capture_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='sponsors/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sponsor principal')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='contests.contest')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
