# Generated by Django 6.0.2 on 2026-03-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0009_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='length_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud (cm)'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='species',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
