# Generated by Django 6.0.2 on 2026-03-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0010_alter_capture_length_cm_alter_capture_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='overlay',
            field=models.ImageField(blank=True, null=True, upload_to='measurements/'),
        ),
    ]
