# Generated by Django 6.0.2 on 2026-03-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0011_capture_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='length_ai',
            field=models.FloatField(blank=True, null=True, verbose_name='Medición IA'),
        ),
        migrations.AlterField(
            model_name='capture',
            name='length_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida oficial (cm)'),
        ),
    ]
