# Generated by Django 6.0.2 on 2026-03-11 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_organization_logo'),
        ('contests', '0012_capture_length_ai_alter_capture_length_cm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capture',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='capture',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='length_ai',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='overlay',
        ),
        migrations.AddField(
            model_name='capture',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='capture',
            name='approved_by',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='capture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='capture',
            name='length_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contest',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_contests', to='clubs.organization'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Inscripción Abierta'), ('RUNNING', 'En Curso'), ('CLOSED', 'Finalizado')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='competitor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
