# Generated by Django 6.0.2 on 2026-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0013_alter_capture_options_alter_contest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contest',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='mode',
            field=models.CharField(choices=[('SELF', 'Autogestionado'), ('PRO', 'Evento profesional')], default='SELF', max_length=10),
        ),
    ]
