# Generated by Django 6.0.2 on 2026-03-02 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nombre completo')),
                ('dni', models.CharField(max_length=20, unique=True, verbose_name='DNI')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('category', models.CharField(choices=[('Hombres', 'Hombres'), ('Mujeres', 'Mujeres'), ('Cadetes', 'Cadetes'), ('Niños', 'Niños')], max_length=20, verbose_name='Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
            ],
            options={
                'verbose_name': 'Pescador',
                'verbose_name_plural': 'Pescadores',
            },
        ),
    ]
