# Generated by Django 6.0.2 on 2026-03-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_organization'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisher',
            options={'ordering': ['full_name'], 'verbose_name': 'Pescador', 'verbose_name_plural': 'Pescadores'},
        ),
        migrations.RemoveField(
            model_name='fisher',
            name='club',
        ),
        migrations.AddField(
            model_name='fisher',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.organization', verbose_name='Club / Peña'),
        ),
    ]
