# Generated by Django 6.0.2 on 2026-03-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_fisher_options_remove_fisher_club_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fisher',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Pescador', 'verbose_name_plural': 'Pescadores'},
        ),
        migrations.AddField(
            model_name='fisher',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='fisher',
            name='first_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='fisher',
            name='last_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='fisher',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='fishers/', verbose_name='Foto de perfil'),
        ),
    ]
