# Generated by Django 6.0.2 on 2026-03-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_fisher_options_fisher_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisher',
            name='category',
            field=models.CharField(choices=[('MEN', 'Hombres'), ('WOMEN', 'Mujeres'), ('CADET', 'Cadetes'), ('SENIOR', 'Señor'), ('CHILDREN', 'Niños')], max_length=10),
        ),
    ]
