# Generated by Django 6.0.2 on 2026-03-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='Provincia')),
                ('country', models.CharField(default='Argentina', max_length=120, verbose_name='País')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
    ]
