# Generated by Django 6.0.2 on 2026-03-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('type', models.CharField(choices=[('CLUB', 'Club'), ('PENA', 'Peña'), ('FED', 'Federación'), ('MUNI', 'Municipalidad'), ('OTRO', 'Otro')], default='CLUB', max_length=10, verbose_name='Tipo')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='Provincia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['name'],
            },
        ),
    ]
