# Generated by Django 6.0.2 on 2026-03-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_organization'),
        ('users', '0002_alter_fisher_options_remove_fisher_club_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
